### ISSUE TITLE
Doc tests for `Range::collect()`

### ISSUE THREAD

**Issue by killercup** [killercup/a-range#10]
`Range`s implement `collect()` and `to_vec()` methods. To illustrate how they can be used, we should add examples to their documentation. These examples should also work as [doc tests](https://doc.rust-lang.org/1.29.2/rustdoc/documentation-tests.html) for the methods.

- For both upward and downward ranges, add an example…
  - [ ] for `collect`ing into a Vec, with a note linking to `to_vec()`
  - [ ] for `to_vec`
  - [ ] for `collect`ing into a non-vec data structure (pick one you like from [here](https://doc.rust-lang.org/1.29.2/std/iter/trait.FromIterator.html#implementors))
- [ ] Remove unit tests that are now covered by the doc tests (like [these](https://github.com/killercup/a-range/blob/ce391ed856e5fb52e9445496ccec046b91359ed5/src/lib.rs#L359-L369))

**Comment by sindreij** [comment]
I'd like to try this.

**Comment by killercup** [comment]
Awesome! Feel free to ask here if you have any questions!
