### ISSUE TITLE
Add documentation and doc test for `from(i).up_to(i)` case

### ISSUE THREAD

**Issue by killercup** [killercup/a-range#12]
In #6, we added

https://github.com/killercup/a-range/blob/ce391ed856e5fb52e9445496ccec046b91359ed5/src/lib.rs#L405-L417

We should

- [ ] document this behavior (either in the crate-level docs or in the docs for `up_to`/`down_to`) and
- [ ] make these unit tests doc tests

**Comment by killercup** [comment]
cc @babhishek21 -- looking at the code, I just noticed we can make this part of the docs

**Comment by babhishek21** [comment]
Yup! Let's make these doc tests. I'll work on this. ✌️
