### ISSUE TITLE
Move crate-level docs into Readme and include it

### ISSUE THREAD

**Issue by killercup** [killercup/a-range#13]
It's a bit of weird dance right now, but we can include the content of the `README.md` file as documentation on nightly.

- [ ] Move content of crate-level docs to `README.md`
- Include the readme
  - [ ] Behind a new `nighty` cargo feature
  - [ ] Actually include it ([like this](https://github.com/yoshuawuyts/css-rel-preload/blob/7223aa9de37d45c791ec8d6671795199da414bfa/src/lib.rs#L2-L3))
  - [ ] Enable the nightly feature on docs.rs (like [this](https://github.com/diesel-rs/diesel/blob/af5f76904907b102f7c4eecc677e00dcacc2a904/diesel/Cargo.toml#L65-L67))

**Comment by eignnx** [comment]
Imma give this a try!

**Comment by killercup** [comment]
Alright! Feel free to ask here if you have any questions!

**Comment by killercup** [comment]
Solved using docmatic in #23
