### ISSUE TITLE
Copy semantics/Trait for a_range::From

### ISSUE THREAD

**Issue by babhishek21** [killercup/a-range#19]
`::From` should have Copy semantics or Traits available (either derived or implemented by us). 

Since multiple ranges can have a single starting point, it makes sense for a user to be able to reuse a `::From` object.

An example:

```rust
let start = a_range::from(10);

let up_range = start.up_to(13); // [10, 11, 12, 13]

let down_range = start.down_to(8); // No copy semantics, so this fails to compile.
```

Formally, this is the kind of compile error I get right now:

```
error[E0382]: use of moved value: `x`
 --> src/lib.rs:27:18
  |
6 | let up_range = x.up_to(10);
  |                - value moved here
7 | let down_range = x.down_to(10);
  |                  ^ value used here after move
  |
  = note: move occurs because `x` has type `a_range::From<i32>`, which does not implement the `Copy` trait
```

**Comment by killercup** [comment]
Since `Idx` requires `Clone`, `From` can also derive `Clone`. I don't want `Idx` to only allow `Copy` types, though.

Copy is also kind of special IIRC. Maybe we can `impl<Idx> Copy for From when Idx: Copy`? Otherwise, this might be difficult.

**Comment by killercup** [comment]
Don't mind me, this is actually quite easy. I'll submit a PR in a minute.
