### ISSUE TITLE
Validate inputs in constructor

### ISSUE THREAD

**Issue by killercup** [killercup/a-range#6]
- [ ] `from(n).up_to(n-1)` should fail
- [ ] `from(n).down_to(n+1)` should fail
- [ ] What should `from(n).up_to(n)` and `from(n).down_to(n+1)` do? Nothing?

**Comment by babhishek21** [comment]
Looks like a good time to learn Rust. Can I work on this?

**Comment by killercup** [comment]
Absolutely! Let me know if you have any questions!

**Comment by babhishek21** [comment]
Hi! would you like me to throw explicit `panic`s or do you have something else in mind?

**Comment by killercup** [comment]
@babhishek21 good question. I'd go with a panic for now, as it's most likely a programmer error; in teh future, we can introduce `try_up_to` and similar if people ask for it.

**Comment by babhishek21** [comment]
@killercup So, I was going to put in `panic`s of the sort:
```
panic!("Cannot count upwards from {} to {}", self.from, x);   // `self.from` and `x` are both of generic type `Idx`
```
But that'd mean putting bounds for `Idx` to be `std::fmt::Display`able (which really shouldn't be hard requirement for consumers of this crate). So how do I keep my `panic`s descriptive enough?

**Comment by killercup** [comment]
Well, you could use debug output (`{:?}`) but that'd require `Debug`, of course. It's implemented by more types, but still a needless constraint.

I'd probably just go with a generic message like "invalid range: upper bound cannot be less than lower bound" (or reverse for… reverse).

Speaking of bounds: Seems like this also means we'll need `PartialOrd` to check of `<=`/`>=`. It's a bit stricter than `PartialEq`, but does make sense over all.

**Comment by babhishek21** [comment]
Yup, I'm putting a bound for `PartialOrd` for `Idx`.
